<template>
  <div class="ai-assistant">
    <div class="card">
      <div class="card-header">
        <h5 class="mb-0">
          <i class="bi bi-robot me-2"></i>
          AI Assistant
        </h5>
        <small class="text-muted">Powered by Claude AI</small>
        <div class="ai-status">
          <span v-if="aiStatus === 'connected'" class="badge bg-success">
            <i class="bi bi-wifi"></i> Connected
          </span>
          <span v-else-if="aiStatus === 'connecting'" class="badge bg-warning">
            <i class="bi bi-arrow-clockwise"></i> Connecting...
          </span>
          <span v-else class="badge bg-danger">
            <i class="bi bi-exclamation-triangle"></i> Offline
          </span>
        </div>
      </div>
      <div class="card-body">
        <!-- Chat Interface -->
        <div class="chat-container" ref="chatContainer">
          <div 
            v-for="(message, index) in chatHistory" 
            :key="index"
            class="message"
            :class="message.role"
          >
            <div class="message-avatar">
              <i :class="message.role === 'user' ? 'bi bi-person' : 'bi bi-robot'"></i>
            </div>
            <div class="message-content">
              <div class="message-text" v-html="formatMessage(message.content)"></div>
              <div class="message-time">{{ formatTime(message.timestamp) }}</div>
              <div v-if="message.role === 'assistant' && message.model" class="message-model">
                <small class="text-muted">Generated by {{ message.model }}</small>
              </div>
            </div>
          </div>
          
          <!-- Loading indicator -->
          <div v-if="isLoading" class="message assistant">
            <div class="message-avatar">
              <i class="bi bi-robot"></i>
            </div>
            <div class="message-content">
              <div class="typing-indicator">
                <span></span>
                <span></span>
                <span></span>
              </div>
              <div class="message-time">Thinking...</div>
            </div>
          </div>
        </div>

        <!-- Quick Actions -->
        <div class="quick-actions mb-3">
          <h6>Quick Questions:</h6>
          <div class="d-flex flex-wrap gap-2">
            <button 
              v-for="suggestion in quickSuggestions" 
              :key="suggestion"
              class="btn btn-outline-primary btn-sm"
              @click="sendMessage(suggestion)"
              :disabled="isLoading || aiStatus !== 'connected'"
            >
              {{ suggestion }}
            </button>
          </div>
        </div>

        <!-- AI Features -->
        <div class="ai-features mb-3" v-if="aiStatus === 'connected'">
          <h6>AI Features:</h6>
          <div class="d-flex flex-wrap gap-2">
            <button 
              class="btn btn-outline-success btn-sm"
              @click="showTaskAnalysis"
              :disabled="isLoading"
            >
              <i class="bi bi-clipboard-check"></i> Task Analysis
            </button>
            <button 
              class="btn btn-outline-info btn-sm"
              @click="showHealthTips"
              :disabled="isLoading"
            >
              <i class="bi bi-heart-pulse"></i> Health Tips
            </button>
          </div>
        </div>

        <!-- Input Area -->
        <div class="input-area">
          <div class="input-group">
            <textarea 
              ref="messageInput"
              class="form-control" 
              placeholder="Ask me anything about the system, tasks, or get help..."
              v-model="currentMessage"
              @keydown.enter.prevent="handleEnter"
              :disabled="isLoading || aiStatus !== 'connected'"
              rows="2"
            ></textarea>
            <button 
              class="btn btn-primary"
              @click="sendMessage(currentMessage)"
              :disabled="!currentMessage.trim() || isLoading || aiStatus !== 'connected'"
            >
              <i class="bi bi-send"></i>
            </button>
          </div>
          <div class="input-actions">
            <button 
              class="btn btn-outline-secondary btn-sm"
              @click="clearChat"
              :disabled="chatHistory.length === 0"
            >
              <i class="bi bi-trash me-1"></i>
              Clear Chat
            </button>
            <button 
              class="btn btn-outline-secondary btn-sm"
              @click="exportChat"
              :disabled="chatHistory.length === 0"
            >
              <i class="bi bi-download me-1"></i>
              Export Chat
            </button>
            <button 
              class="btn btn-outline-warning btn-sm"
              @click="testConnection"
              :disabled="isLoading"
            >
              <i class="bi bi-arrow-clockwise me-1"></i>
              Test Connection
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- AI Features Panel -->
    <div class="row mt-4">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h6 class="mb-0">
              <i class="bi bi-magic me-2"></i>
              AI Features
            </h6>
          </div>
          <div class="card-body">
            <div class="feature-list">
              <div class="feature-item">
                <i class="bi bi-check-circle text-success"></i>
                <span>Real-time AI Responses</span>
              </div>
              <div class="feature-item">
                <i class="bi bi-check-circle text-success"></i>
                <span>Task Analysis & Recommendations</span>
              </div>
              <div class="feature-item">
                <i class="bi bi-check-circle text-success"></i>
                <span>Health & Wellness Tips</span>
              </div>
              <div class="feature-item">
                <i class="bi bi-check-circle text-success"></i>
                <span>Personalized Assistance</span>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h6 class="mb-0">
              <i class="bi bi-graph-up me-2"></i>
              Usage Statistics
            </h6>
          </div>
          <div class="card-body">
            <div class="stats-grid">
              <div class="stat-item">
                <div class="stat-number">{{ usageStats.totalConversations }}</div>
                <div class="stat-label">Conversations</div>
              </div>
              <div class="stat-item">
                <div class="stat-number">{{ usageStats.totalMessages }}</div>
                <div class="stat-label">Messages</div>
              </div>
              <div class="stat-item">
                <div class="stat-number">{{ usageStats.averageResponseTime }}s</div>
                <div class="stat-label">Avg Response</div>
              </div>
              <div class="stat-item">
                <div class="stat-number">{{ usageStats.successRate }}%</div>
                <div class="stat-label">Success Rate</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Task Analysis Modal -->
    <div class="modal fade" id="taskAnalysisModal" tabindex="-1">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">AI Task Analysis</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
          </div>
          <div class="modal-body">
            <div class="mb-3">
              <label class="form-label">Task Description:</label>
              <textarea 
                class="form-control" 
                v-model="taskAnalysisForm.description" 
                rows="3"
                placeholder="Describe the task you need help with..."
              ></textarea>
            </div>
            <div class="row">
              <div class="col-md-6">
                <label class="form-label">Task Type:</label>
                <select class="form-select" v-model="taskAnalysisForm.type">
                  <option value="">Select type...</option>
                  <option value="shopping">Shopping</option>
                  <option value="housework">Housework</option>
                  <option value="companionship">Companionship</option>
                  <option value="health">Health</option>
                  <option value="transportation">Transportation</option>
                  <option value="other">Other</option>
                </select>
              </div>
              <div class="col-md-6">
                <label class="form-label">User Context:</label>
                <select class="form-select" v-model="taskAnalysisForm.context">
                  <option value="elderly">Elderly User</option>
                  <option value="volunteer">Volunteer</option>
                  <option value="admin">Admin</option>
                </select>
              </div>
            </div>
            <div v-if="taskAnalysisResult" class="mt-3">
              <h6>AI Analysis:</h6>
              <div class="analysis-result" v-html="formatMessage(taskAnalysisResult)"></div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button 
              type="button" 
              class="btn btn-primary" 
              @click="analyzeTask"
              :disabled="!taskAnalysisForm.description || isLoading"
            >
              <span v-if="isLoading" class="spinner-border spinner-border-sm me-2"></span>
              Analyze Task
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Health Tips Modal -->
    <div class="modal fade" id="healthTipsModal" tabindex="-1">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">AI Health Tips</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-md-4">
                <label class="form-label">Health Topic:</label>
                <select class="form-select" v-model="healthTipsForm.topic">
                  <option value="">Select topic...</option>
                  <option value="general wellness">General Wellness</option>
                  <option value="exercise">Exercise</option>
                  <option value="nutrition">Nutrition</option>
                  <option value="mental health">Mental Health</option>
                  <option value="medication">Medication</option>
                  <option value="safety">Safety</option>
                </select>
              </div>
              <div class="col-md-4">
                <label class="form-label">Age Group:</label>
                <select class="form-select" v-model="healthTipsForm.age">
                  <option value="">Select age...</option>
                  <option value="60-70">60-70</option>
                  <option value="70-80">70-80</option>
                  <option value="80-90">80-90</option>
                  <option value="90+">90+</option>
                </select>
              </div>
              <div class="col-md-4">
                <label class="form-label">Health Condition:</label>
                <select class="form-select" v-model="healthTipsForm.condition">
                  <option value="">Select condition...</option>
                  <option value="general">General</option>
                  <option value="diabetes">Diabetes</option>
                  <option value="hypertension">Hypertension</option>
                  <option value="arthritis">Arthritis</option>
                  <option value="heart">Heart Condition</option>
                  <option value="mobility">Mobility Issues</option>
                </select>
              </div>
            </div>
            <div v-if="healthTipsResult" class="mt-3">
              <h6>AI Health Tips:</h6>
              <div class="health-tips-result" v-html="formatMessage(healthTipsResult)"></div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button 
              type="button" 
              class="btn btn-primary" 
              @click="getHealthTips"
              :disabled="!healthTipsForm.topic || isLoading"
            >
              <span v-if="isLoading" class="spinner-border spinner-border-sm me-2"></span>
              Get Health Tips
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, onMounted, nextTick, watch } from 'vue';
import { useToast } from 'vue-toastification';
import { Modal } from 'bootstrap';
import enhancedAIService from '../services/enhancedAIService';

export default {
  name: 'AIAssistant',
  setup() {
    const toast = useToast();
    
    // Chat state
    const chatContainer = ref(null);
    const messageInput = ref(null);
    const currentMessage = ref('');
    const chatHistory = ref([]);
    const isLoading = ref(false);
    const aiStatus = ref('connecting');
    const userRole = ref('user'); // Add user role state
    
    // Usage statistics
    const usageStats = ref({
      totalConversations: 0,
      totalMessages: 0,
      averageResponseTime: 0,
      successRate: 100
    });

    // Task analysis form
    const taskAnalysisForm = ref({
      description: '',
      type: '',
      context: ''
    });
    const taskAnalysisResult = ref('');

    // Health tips form
    const healthTipsForm = ref({
      topic: '',
      age: '',
      condition: ''
    });
    const healthTipsResult = ref('');

    // Get user role from localStorage
    const getUserRole = () => {
      try {
        const userStr = localStorage.getItem('currentUser');
        if (userStr) {
          const user = JSON.parse(userStr);
          return user.role || 'user';
        }
      } catch (error) {
        console.error('Failed to parse user information:', error);
      }
      return 'user';
    };

    // Initialize user role
    const initUserRole = () => {
      userRole.value = getUserRole();
    };

    // Quick suggestions based on user role
    const getQuickSuggestions = () => {
      const baseSuggestions = [
      'How do I create a new task?',
      'How can I improve my rating?',
      'Tell me about health services',
      'Help me with system navigation'
    ];

      if (userRole.value === 'elderly') {
        return [
          ...baseSuggestions,
          'How do I rate a volunteer?',
          'How do I book a health appointment?',
          'What types of tasks can I create?',
          'How do I check my task status?'
        ];
      } else if (userRole.value === 'volunteer') {
        return [
          ...baseSuggestions,
          'How do I accept a task?',
          'What are the best practices for volunteers?',
          'How do I complete a task?',
          'How can I improve my volunteer rating?'
        ];
      } else if (userRole.value === 'admin') {
        return [
          ...baseSuggestions,
          'How do I manage users?',
          'How do I send bulk emails?',
          'How do I view system statistics?',
          'How do I manage health services?'
        ];
      }

      return baseSuggestions;
    };

    const quickSuggestions = getQuickSuggestions();

    // Test AI connection
    const testConnection = async () => {
      try {
        isLoading.value = true;
        const startTime = Date.now();
        
        const result = await enhancedAIService.callAIAssistant('Hello, can you hear me?');
        
        const responseTime = (Date.now() - startTime) / 1000;
        usageStats.value.averageResponseTime = responseTime;
        
        if (result.success) {
          aiStatus.value = 'connected';
          toast.success('AI connection successful!');
          addMessage('assistant', result.response, 'silicon-flow-qwen2.5');
        } else {
          throw new Error('AI response failed');
        }
      } catch (error) {
        console.error('Connection test failed:', error);
        aiStatus.value = 'offline';
        toast.error('AI connection failed. Using fallback mode.');
      } finally {
        isLoading.value = false;
      }
    };

    // Load chat history from localStorage
    const loadChatHistory = () => {
      try {
        const saved = localStorage.getItem('ai_chat_history');
        if (saved) {
          const parsed = JSON.parse(saved);
          // Only load if it's from today (to avoid old conversations)
          const today = new Date().toDateString();
          if (parsed.date === today && Array.isArray(parsed.history)) {
            chatHistory.value = parsed.history.map(msg => ({
              ...msg,
              timestamp: new Date(msg.timestamp)
            }));
            return true;
          }
        }
      } catch (error) {
        console.warn('Failed to load chat history:', error);
      }
      return false;
    };

    // Save chat history to localStorage
    const saveChatHistory = () => {
      try {
        const toSave = {
          date: new Date().toDateString(),
          history: chatHistory.value
        };
        localStorage.setItem('ai_chat_history', JSON.stringify(toSave));
      } catch (error) {
        console.warn('Failed to save chat history:', error);
      }
    };

    // Initialize AI Assistant
    const initializeAI = async () => {
      // Load existing chat history first
      const hasHistory = loadChatHistory();

      // Set AI status to connected immediately to avoid browser extension conflicts
      aiStatus.value = 'connected';

      try {
        // Use a safer initialization approach
        setTimeout(async () => {
          try {
            const testResult = await enhancedAIService.testConnection();
            if (testResult.provider === 'claude') {
              toast.success('AI Assistant ready (Claude AI) - Powered by Anthropic Claude technology');
            } else if (testResult.provider === 'local-ai') {
              toast.success('AI Assistant ready (Advanced Local AI) - Providing intelligent, context-aware responses');
            } else if (testResult.provider === 'silicon-flow') {
              toast.success('AI Assistant ready (Silicon Flow AI) - Real AI powered responses');
            } else if (testResult.provider === 'enhanced-mock') {
              toast.success('AI Assistant ready (Smart Mode) - Providing intelligent responses');
            } else {
              toast.success(`AI Assistant ready (${testResult.provider})`);
            }
          } catch (error) {
            console.warn('AI test connection failed, but continuing in safe mode:', error);
            toast.success('AI Assistant ready (Safe Mode)');
          }
        }, 100); // Small delay to avoid extension conflicts

      } catch (error) {
        console.warn('AI initialization error:', error);
        // Still set as connected since we have mock responses
        aiStatus.value = 'connected';
        toast.success('AI Assistant ready (Safe Mode)');
      }

      // Only add welcome message if no history exists
      if (!hasHistory) {
        // Get personalized welcome message based on user role
        const getWelcomeMessage = () => {
        const baseMessage = `Hello! I'm your AI assistant for the Evergreen Way platform. I'm powered by Claude AI technology and ready to provide intelligent, helpful responses.`;

        if (userRole.value === 'elderly') {
          return `${baseMessage}

As an elderly user, I can help you with:
• **Task Management**: Creating and tracking help requests
• **Volunteer Services**: Understanding how volunteers can assist you
• **Health Appointments**: Booking and managing health services
• **Rating System**: How to rate volunteers after service
• **System Navigation**: Finding features and getting help

Testing connection to AI services...`;
        } else if (userRole.value === 'volunteer') {
          return `${baseMessage}

As a volunteer, I can help you with:
• **Task Acceptance**: How to find and accept tasks
• **Service Best Practices**: Tips for providing excellent service
• **Task Completion**: How to properly complete and update tasks
• **Rating Improvement**: How to maintain high ratings
• **System Navigation**: Finding features and getting help

Testing connection to AI services...`;
        } else if (userRole.value === 'admin') {
          return `${baseMessage}

As an administrator, I can help you with:
• **User Management**: Managing elderly and volunteer accounts
• **System Monitoring**: Viewing statistics and system health
• **Email Management**: Sending bulk emails and notifications
• **Service Management**: Managing health services and events
• **Data Analysis**: Understanding system usage and trends

Testing connection to AI services...`;
        }

        return `${baseMessage}

I can help you with:
• **Task Management**: Creating, editing, and tracking tasks
• **System Navigation**: Finding features and understanding the interface
• **Best Practices**: Tips for volunteers and elderly users
• **Health & Wellness**: Information about health services and activities
• **General Support**: Any questions about the Evergreen Way system

Testing connection to AI services...`;
        };

        // Add welcome message
        addMessage('assistant', getWelcomeMessage());

        // Test connection
        testConnection();
      }
    };

    // Add message to chat
    const addMessage = (role, content, model = null) => {
      chatHistory.value.push({
        role,
        content,
        timestamp: new Date(),
        model
      });
      
      // Update stats
      if (role === 'user') {
        usageStats.value.totalMessages++;
      }

      // Auto-save chat history
      saveChatHistory();

      // Scroll to bottom
      nextTick(() => {
        scrollToBottom();
      });
    };

    // Send message
    const sendMessage = async (message) => {
      if (!message.trim() || isLoading.value) return;
      
      const userMessage = message.trim();
      currentMessage.value = '';
      
      // Add user message
      addMessage('user', userMessage);
      
      // Show loading
      isLoading.value = true;
      
      try {
        const startTime = Date.now();
        
        // Use enhanced AI service
        const conversationHistory = chatHistory.value
          .filter(msg => msg.role !== 'system')
          .slice(-10) // Keep last 10 messages for context
          .map(msg => ({ role: msg.role, content: msg.content }));

        const result = await enhancedAIService.callAIAssistant(userMessage, conversationHistory);

        if (result.success) {
          addMessage('assistant', result.response, result.provider);
          usageStats.value.totalConversations++;
          usageStats.value.successRate = 100;

          // Update AI status based on provider
          if (result.provider === 'gemini') {
            aiStatus.value = 'connected';
          } else if (result.provider === 'mock') {
            aiStatus.value = 'offline';
            toast.warning('Using fallback AI responses');
          }
        } else {
          throw new Error(result.error || 'AI response failed');
        }
        
        // Update response time
        const responseTime = (Date.now() - startTime) / 1000;
        usageStats.value.averageResponseTime = responseTime;
        
      } catch (error) {
        console.error('AI response error:', error);

        // Fallback to offline mode
        aiStatus.value = 'offline';
        const fallbackMessage = "I apologize, but I'm having trouble connecting to the AI service right now. Please try again later or contact support for immediate assistance.";
        addMessage('assistant', fallbackMessage, 'error');

        toast.error('AI service unavailable. Please try again later.');
        usageStats.value.successRate = Math.max(0, usageStats.value.successRate - 10);
      } finally {
        isLoading.value = false;
      }
    };

    // Show task analysis modal
    const showTaskAnalysis = () => {
      const modal = new Modal(document.getElementById('taskAnalysisModal'));
      modal.show();
    };

    // Analyze task
    const analyzeTask = async () => {
      if (!taskAnalysisForm.value.description) return;

      try {
        isLoading.value = true;

        // Use AI assistant to analyze task
        const prompt = `Please analyze this task: "${taskAnalysisForm.value.description}". Task type: ${taskAnalysisForm.value.type}. Context: ${taskAnalysisForm.value.context}.

Please provide:
1. Task complexity assessment
2. Estimated time required
3. Required skills or resources
4. Potential challenges
5. Recommendations for successful completion
6. Safety considerations (if applicable)`;

        const result = await enhancedAIService.callAIAssistant(prompt);

        if (result.success) {
          taskAnalysisResult.value = result.response;
          toast.success('Task analysis completed!');
        } else {
          throw new Error('Task analysis failed');
        }
      } catch (error) {
        console.error('Task analysis error:', error);
        toast.error('Failed to analyze task. Please try again.');
        // Provide fallback analysis
        taskAnalysisResult.value = `Task Analysis for: ${taskAnalysisForm.value.description}\n\nType: ${taskAnalysisForm.value.type}\n\nGeneral Recommendations:\n• Break down the task into smaller steps\n• Ensure you have necessary resources\n• Consider safety precautions\n• Allow adequate time for completion\n• Ask for help if needed\n\nFor detailed analysis, please try again or consult with a volunteer coordinator.`;
      } finally {
        isLoading.value = false;
      }
    };

    // Show health tips modal
    const showHealthTips = () => {
      const modal = new Modal(document.getElementById('healthTipsModal'));
      modal.show();
    };

    // Get health tips
    const getHealthTips = async () => {
      if (!healthTipsForm.value.topic) return;

      try {
        isLoading.value = true;

        // Use AI assistant to generate health tips
        const prompt = `Please provide health tips for ${healthTipsForm.value.topic} for a ${healthTipsForm.value.age} year old person${healthTipsForm.value.condition ? ` with ${healthTipsForm.value.condition}` : ''}. Please provide practical, safe, and helpful advice.`;

        const result = await enhancedAIService.callAIAssistant(prompt);

        if (result.success) {
          healthTipsResult.value = result.response;
          toast.success('Health tips generated!');
        } else {
          throw new Error('Health tips generation failed');
        }
      } catch (error) {
        console.error('Health tips error:', error);
        toast.error('Failed to get health tips. Please try again.');
        // Provide fallback health tips
        healthTipsResult.value = `Here are some general health tips for ${healthTipsForm.value.topic}:\n\n• Stay hydrated by drinking plenty of water\n• Maintain a balanced diet with fruits and vegetables\n• Get regular exercise appropriate for your age\n• Ensure adequate sleep (7-9 hours per night)\n• Regular check-ups with healthcare providers\n• Practice stress management techniques\n\nPlease consult with healthcare professionals for personalized advice.`;
      } finally {
        isLoading.value = false;
      }
    };

    // Handle Enter key
    const handleEnter = (event) => {
      if (event.shiftKey) {
        // Allow new line with Shift+Enter
        return;
      }
      sendMessage(currentMessage.value);
    };

    // Scroll to bottom
    const scrollToBottom = () => {
      if (chatContainer.value) {
        chatContainer.value.scrollTop = chatContainer.value.scrollHeight;
      }
    };

    // Clear chat
    const clearChat = () => {
      if (confirm('Are you sure you want to clear the chat history?')) {
        chatHistory.value = [];
        localStorage.removeItem('ai_chat_history');
        initializeAI();
        toast.info('Chat history cleared');
      }
    };

    // Export chat
    const exportChat = () => {
      const chatText = chatHistory.value.map(msg => 
        `[${msg.role.toUpperCase()}] ${formatTime(msg.timestamp)}\n${msg.content}\n`
      ).join('\n');
      
      const blob = new Blob([chatText], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `ai-chat-${new Date().toISOString().split('T')[0]}.txt`;
      link.click();
      URL.revokeObjectURL(url);
      
      toast.success('Chat exported successfully');
    };

    // Format message content
    const formatMessage = (content) => {
      // Convert markdown-like formatting to HTML
      return content
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/\*(.*?)\*/g, '<em>$1</em>')
        .replace(/\n/g, '<br>')
        .replace(/•/g, '&bull;');
    };

    // Format time
    const formatTime = (timestamp) => {
      return new Date(timestamp).toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit'
      });
    };

    // Watch for new messages to scroll
    watch(chatHistory, () => {
      nextTick(() => {
        scrollToBottom();
      });
    });

    onMounted(() => {
      // Clear any browser extension errors
      try {
        if (typeof chrome !== 'undefined' && chrome.runtime) {
          chrome.runtime.lastError = null;
        }
      } catch (e) {
        // Ignore extension-related errors
      }

      initUserRole(); // Initialize user role on mount

      // Delay AI initialization to avoid extension conflicts
      setTimeout(() => {
        initializeAI();
      }, 300);
    });

    return {
      chatContainer,
      messageInput,
      currentMessage,
      chatHistory,
      isLoading,
      aiStatus,
      userRole,
      usageStats,
      quickSuggestions,
      taskAnalysisForm,
      taskAnalysisResult,
      healthTipsForm,
      healthTipsResult,
      sendMessage,
      handleEnter,
      clearChat,
      exportChat,
      formatMessage,
      formatTime,
      testConnection,
      showTaskAnalysis,
      analyzeTask,
      showHealthTips,
      getHealthTips
    };
  }
};
</script>

<style scoped>
.ai-assistant {
  max-width: 1000px;
  margin: 0 auto;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.ai-status {
  margin-left: auto;
}

.chat-container {
  height: 400px;
  overflow-y: auto;
  border: 1px solid #dee2e6;
  border-radius: 8px;
  padding: 1rem;
  background: #f8f9fa;
  margin-bottom: 1rem;
}

.message {
  display: flex;
  margin-bottom: 1rem;
  align-items: flex-start;
}

.message.user {
  flex-direction: row-reverse;
}

.message-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 0.5rem;
  flex-shrink: 0;
}

.message.user .message-avatar {
  background: #007bff;
  color: white;
}

.message.assistant .message-avatar {
  background: #28a745;
  color: white;
}

.message-content {
  max-width: 70%;
  background: white;
  padding: 0.75rem;
  border-radius: 12px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

.message.user .message-content {
  background: #007bff;
  color: white;
}

.message-text {
  line-height: 1.5;
  margin-bottom: 0.25rem;
}

.message-time {
  font-size: 0.75rem;
  opacity: 0.7;
  text-align: right;
}

.message-model {
  font-size: 0.7rem;
  opacity: 0.6;
  margin-top: 0.25rem;
}

.typing-indicator {
  display: flex;
  gap: 0.25rem;
  padding: 0.5rem;
}

.typing-indicator span {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #007bff;
  animation: typing 1.4s infinite ease-in-out;
}

.typing-indicator span:nth-child(1) { animation-delay: -0.32s; }
.typing-indicator span:nth-child(2) { animation-delay: -0.16s; }

@keyframes typing {
  0%, 80%, 100% { transform: scale(0); }
  40% { transform: scale(1); }
}

.quick-actions,
.ai-features {
  border-top: 1px solid #dee2e6;
  padding-top: 1rem;
}

.input-area {
  border-top: 1px solid #dee2e6;
  padding-top: 1rem;
}

.input-actions {
  display: flex;
  gap: 0.5rem;
  margin-top: 0.5rem;
  justify-content: flex-end;
}

.feature-list {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.feature-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.stats-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
}

.stat-item {
  text-align: center;
  padding: 1rem;
  background: #f8f9fa;
  border-radius: 8px;
}

.stat-number {
  font-size: 1.5rem;
  font-weight: bold;
  color: #007bff;
}

.stat-label {
  font-size: 0.875rem;
  color: #6c757d;
  margin-top: 0.25rem;
}

.analysis-result,
.health-tips-result {
  background: #f8f9fa;
  padding: 1rem;
  border-radius: 8px;
  border-left: 4px solid #007bff;
  max-height: 300px;
  overflow-y: auto;
}

/* Responsive design */
@media (max-width: 768px) {
  .chat-container {
    height: 300px;
  }
  
  .message-content {
    max-width: 85%;
  }
  
  .stats-grid {
    grid-template-columns: 1fr;
  }
  
  .input-actions {
    flex-direction: column;
  }
  
  .card-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 0.5rem;
  }
  
  .ai-status {
    margin-left: 0;
  }
}

/* Scrollbar styling */
.chat-container::-webkit-scrollbar,
.analysis-result::-webkit-scrollbar,
.health-tips-result::-webkit-scrollbar {
  width: 6px;
}

.chat-container::-webkit-scrollbar-track,
.analysis-result::-webkit-scrollbar-track,
.health-tips-result::-webkit-scrollbar-track {
  background: #f1f1f1;
  border-radius: 3px;
}

.chat-container::-webkit-scrollbar-thumb,
.analysis-result::-webkit-scrollbar-thumb,
.health-tips-result::-webkit-scrollbar-thumb {
  background: #c1c1c1;
  border-radius: 3px;
}

.chat-container::-webkit-scrollbar-thumb:hover,
.analysis-result::-webkit-scrollbar-thumb:hover,
.health-tips-result::-webkit-scrollbar-thumb:hover {
  background: #a8a8a8;
}
</style>
